// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq8cel5eVej3O_43E0iKqmRyXb7-J8jn8',
    appId: '1:274728567561:web:57f36d627102070b4449d8',
    messagingSenderId: '274728567561',
    projectId: 'greengo-db',
    authDomain: 'greengo-db.firebaseapp.com',
    storageBucket: 'greengo-db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk2B-x13hU7kmrFwf491yJUb8AFXpHHbc',
    appId: '1:274728567561:android:033b1ba00ced35bc4449d8',
    messagingSenderId: '274728567561',
    projectId: 'greengo-db',
    storageBucket: 'greengo-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQP-VwlBDccxqHvJ5AO9zDAD2MUM4lWTw',
    appId: '1:274728567561:ios:f72b8b592cfe6bcb4449d8',
    messagingSenderId: '274728567561',
    projectId: 'greengo-db',
    storageBucket: 'greengo-db.appspot.com',
    iosClientId: '274728567561-n26i565kaumul4m59v7tq50b6i0641j9.apps.googleusercontent.com',
    iosBundleId: 'com.example.greengo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQP-VwlBDccxqHvJ5AO9zDAD2MUM4lWTw',
    appId: '1:274728567561:ios:f72b8b592cfe6bcb4449d8',
    messagingSenderId: '274728567561',
    projectId: 'greengo-db',
    storageBucket: 'greengo-db.appspot.com',
    iosClientId: '274728567561-n26i565kaumul4m59v7tq50b6i0641j9.apps.googleusercontent.com',
    iosBundleId: 'com.example.greengo',
  );
}
